tcpIngressRoute:
  enabled: true
  name: jellyfin
  entryPoints:
    - websecure
  hostSNI: jellyfin.jadogg.com

service:
  name: jellyfin-ext
  type: ExternalName
  externalName: 10.0.1.50
  port: 30013
