apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.service.name }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
subsets:
  - addresses:
      - ip: {{ .Values.service.externalName }}
    ports:
      - name: tcp
        port: {{ .Values.service.port }}
        protocol: TCP
