{{- if .Values.tcpIngressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.tcpIngressRoute.name }}
spec:
  entryPoints:
    {{- toYaml .Values.tcpIngressRoute.entryPoints | nindent 4 }}
  routes:
    - match: HostSNI(`{{ .Values.tcpIngressRoute.hostSNI }}`)
      services:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
  tls:
    passthrough: true
{{- end }}