{{- if .Values.service.type }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.service.externalName }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
