apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
subsets:
  - addresses:
      - ip: 10.0.1.50
    ports:
      - name: http
        port: 80
        protocol: TCP
