apiVersion: v2
name: monitoring
description: Wrapper for kube-prometheus-stack
version: 0.1.0
type: application

dependencies:
  - name: kube-prometheus-stack
    version: 80.4.1
    repository: https://prometheus-community.github.io/helm-charts
