# infrastructure/minio/values.yaml


persistence:
  enabled: true
  storageClass: longhorn # use replication (2) 
  size: 25Gi
  accessMode: ReadWriteOnce

existingSecret: minio-creds  # use secrets 
rootUser: "" 
rootPassword: ""

resources:
  requests:
    memory: 512Mi
