apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: truenas
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - url: "https://10.0.1.50"
    serversTransport: insecure-transport

