# 1. The Service
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: traefik
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
# 2. The Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas 
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.1.50
    ports:
      - name: https
        port: 443
