apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.jadogg.com`)
      kind: Rule
      services:
        - name: truenas   # Points to the Standard Service we made above
          kind: Service   # Changed from TraefikService to Service
          port: 443
          # We attach the transport HERE now:
          serversTransport: insecure-transport
  tls:
    secretName: jadogg-wildcard-cert
