service:
  main:
    type: ExternalName
    externalName: 10.0.1.50
    port: 80

ingress:
  main:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-truenas-stripprefix@kubernetescrd
    hosts:
      - host: truenas.jadogg.com
        paths:
          - path: /ui
            pathType: Prefix
    tls:
      - secretName: jadogg-wildcard-cert
        hosts:
          - truenas.jadogg.com
